Dev
GoRunMaxim/Reverse pull request #1
Opened 2020-12-08 14:47 UTC by GoRunMaxim

Adding project version for review

2020-12-08 20:21 UTC, GoRunMaxim commented
Things that I had previously and now fixed:

- Test cases structure (no more "request, response, error field")
- Naming
- Added description to readme for modules
- Fixed strings errors (From uppercase to lowercase)
- Fixed "empty string error", now the func just return empty string again

2020-12-09 08:37 UTC, papahmsolo requested changes
Nice!

- Add rules to gitirnore, you probably don't want to have `.idea` files in your repo.

2020-12-09 08:44 UTC, GoRunMaxim commented
**Add rules to gitirnore, you probably don't want to have .idea files in your repo.**

I edited .gitignore file, so he doesn't pull my .idea file to my  repository;

2020-12-09 08:49 UTC, papahmsolo requested changes

2020-12-09 08:49 UTC, papahmsolo commented on String/string_test.go
> +}
We don't need to export this type, do we?
Also, what is the difference between `want` and `expect`? Your test case should probably have a `str string` and `want string` that we expect :)

2020-12-09 08:49 UTC, papahmsolo commented on String/go.mod
> +)
I'm not sure if we want that in the repo/ What are these dependencies for? We don't use them in the program.

2020-12-09 08:49 UTC, papahmsolo commented on String/go.mod
> +module String
Pick some unique name for your module, if you look at the other modules you'll notice the module name is matching the address of the repo.

2020-12-09 08:53 UTC, papahmsolo commented on String/string_test.go
> +}
We can also avoid creating a new type by just declaring the tests with the slice literal:
```
var tests = []struct {
	str    string
	expect string
}{
/// test cases go here
}
```

2020-12-09 09:00 UTC, papahmsolo commented on String/string.go
> +
Too many empty lines :)

2020-12-09 09:29 UTC, GoRunMaxim commented
Changes after review:

- Deleted empty space in string.go

- Changed module naming

- Changed cases struct

- Modified go.mod file

2020-12-09 12:38 UTC, papahmsolo requested changes
Try running `golint` now it should give you some warnings :)

2020-12-09 12:38 UTC, papahmsolo commented on String/go.sum
> +github.com/kisielk/gotool v1.0.0 h1:AV2c/EiW3KqPNT9ZKl07ehoAGi4C5/01Cfbblndcapg=
`go.sum` should be empty since we don't have any dependencies in our module. `go mod tidy` can help here

2020-12-09 12:38 UTC, papahmsolo commented on String/string.go
> +}
add a new line at the end

2020-12-09 13:16 UTC, GoRunMaxim commented on String/string_test.go
> +}
Done ✅

2020-12-09 13:19 UTC, GoRunMaxim commented on String/string.go
> +
Fixed ✅

2020-12-09 13:21 UTC, GoRunMaxim commented on String/go.sum
> +github.com/kisielk/gotool v1.0.0 h1:AV2c/EiW3KqPNT9ZKl07ehoAGi4C5/01Cfbblndcapg=
Fixed ✅

2020-12-09 13:21 UTC, GoRunMaxim commented on String/string.go
> +}
Done ✅

2020-12-09 13:22 UTC, GoRunMaxim commented on String/go.mod
> +module String
Changed to StrReverse (don't know if that is good decision 🧐)

2020-12-09 13:57 UTC, papahmsolo commented on String/string_test.go
> +}
Cool!

2020-12-09 14:32 UTC, papahmsolo requested changes
See comments

2020-12-09 14:32 UTC, papahmsolo commented on String/go.sum
> +github.com/kisielk/gotool v1.0.0 h1:AV2c/EiW3KqPNT9ZKl07ehoAGi4C5/01Cfbblndcapg=
Doesn't seem like it's been fixed :) The content is still there

2020-12-09 14:32 UTC, papahmsolo commented on String/string.go
> +}
New line maybe?

2020-12-09 14:32 UTC, papahmsolo commented on String/string.go
> +package string
Add a package comment, please

2020-12-09 14:32 UTC, papahmsolo commented on String/string.go
> +//Reverse reverse and return string
I think adding a space after the comment wouldn't harm)
Something like this would do `// Reverse reverses a string`

2020-12-09 14:32 UTC, papahmsolo commented on String/string_test.go
> +	var tests = []struct{
Use short variable declaration when possible

2020-12-09 14:32 UTC, papahmsolo commented on String/string_test.go
> +	}
- It's common to have short but meaningful names. You may want to rename `id`, `item`, `result` See https://github.com/golang/go/wiki/CodeReviewComments#variable-names
- We don't really need the number(`id` here) of the test, do we? we just need to know what's wrong
- Do we need to use `DeepEqual` for strings?
- We can save up a variable declaration by passing `item.expect`  to `t.Fatalf`

2020-12-09 14:59 UTC, GoRunMaxim commented on String/string_test.go
> +	var tests = []struct{
Changed to :=

2020-12-09 15:18 UTC, GoRunMaxim commented on String/string_test.go
> +	}
**Added explanation for package**

Wrong commits naming. Should be "Change tests struct names"

2020-12-09 15:18 UTC, GoRunMaxim commented on String/string.go
> +package string
✅

2020-12-09 15:18 UTC, GoRunMaxim commented on String/string.go
> +}
☑️

2020-12-09 20:47 UTC, papahmsolo commented on String/string.go
> +//Reverse reverse and return string
This comment sounds a bit cumbersome in English `Reverse reverse and return`. What does this function do? It _reverses_ a string.

2020-12-09 20:55 UTC, GoRunMaxim commented on String/string.go
> +//Reverse reverse and return string
Such a shame 🙃 Fixed

2020-12-09 21:01 UTC, papahmsolo reviewed
Last but not least, how did you get the test strings reversed? :)

2020-12-09 21:01 UTC, papahmsolo commented on String/string_test.go
> +			t.Fatalf("result not match\ngot : %#v\nwant: %#v", got, test.want)
Also, do we want to exit immediately? `t.Errorf()` allows us to see other tests failure too.

2020-12-09 21:02 UTC, papahmsolo commented on String/string.go
> +//Reverse reverse and return string
No worries, we're not native speakers ;)

2020-12-09 21:07 UTC, papahmsolo commented on String/go.mod
> +module StrReverse
Look at this module name for example - https://github.com/sirupsen/logrus/blob/master/go.mod
You can name your module by analogy.

2020-12-09 21:20 UTC, GoRunMaxim commented on String/string_test.go
> +			t.Fatalf("result not match\ngot : %#v\nwant: %#v", got, test.want)
**Last but not least, how did you get the test strings reversed? :)**

https://codebeautify.org/reverse-string. This website helped me to make tests

**Simply wrong result , maybe?**

If we already has strings error, do we really need to write "result not match" or "wrong result", we can simply write "got ... want ..." (In only this example!)

**Also, do we want to exit immediately? t.Errorf() allows us to see other tests failures too.**

Depends on kind of tests and programs logic. My logic is its easier to debug 1 by 1 that has too many mistakes. So Imho in this case Fatalf is better

2020-12-10 10:18 UTC, papahmsolo requested changes
- `go.sum` is empty we can simply delete it as it's not needed when there are no dependenicies
- you have only one package in this module. you can move `string.go` and `string_test.go` to the root of the project and delete the `String` folder.

2020-12-10 10:18 UTC, papahmsolo commented on String/string_test.go
> +			t.Fatalf("result not match\ngot : %#v\nwant: %#v", got, test.want)
- Okay, if you want to leave it with `Fatalf()` I'm fine with that, but generally, it does no harm to continue run the tests, you'll simply get more info to debug your code.
- I agree with you, error message could be quite simple, like `"Expected: %q, but got: %q"`

2020-12-10 10:18 UTC, papahmsolo commented on String/string.go
> +func Reverse(s string) string{
Looks like the file is not formatted with `goimports`, try running `gofmt -l ./String` in the root of your project it'll show you the list of files that need formatting.

2020-12-10 11:26 UTC, papahmsolo requested changes
Looks very good! Some small tweaks.

2020-12-10 11:26 UTC, papahmsolo commented on reverse.go
> +package Reverse
Package manes should be in lower case by convention: https://golang.org/doc/effective_go.html#package-names
Don't forget about the `go.mod`

2020-12-10 11:26 UTC, papahmsolo commented on reverse_test.go
> +			t.Fatalf("Expected : %s,but got : %s", test.want, got)
Using `%q` will let you distinguish between the error message and the test case values.

2020-12-10 12:00 UTC, papahmsolo approved these changes

2020-12-10 12:02 UTC, merged